# As YAML Configuration File
http:
  routers:
    router-consul:
      entrypoints:
        - "web"
      service: consul-service
      rule: "Host(`consul.home.local`)"

  services:
    consul-service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.152:8500"