# As YAML Configuration File
http:
  routers:
    router-omv6:
      entrypoints:
        - "web"
      service: omv6-service
      rule: "Host(`omv.home.local`)"

  services:
    omv6-service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.77:80"