---

- name: Install Docker Python library
  pip:
    name: docker
    version: 5.0.3
    state: present
  tags: ["docker", pip]

- name: Install jsondiff Python library
  tags: ["pip"]
  pip:
    name: jsondiff
